Page({
  data:{
    entities:[
      {
        imageUrl:'../../assets/images/landscape.png',
        title:'a',
        description:'aa'
      },
      {
        imageUrl:'../../assets/images/landscape.png',
        title:'b',
        description:'bb'
      },
      {
        imageUrl:'../../assets/images/landscape.png',
        title:'c',
        description:'cc'
      },
      {
        imageUrl:'../../assets/images/landscape.png',
        title:'a',
        description:'aa'
      },
      {
        imageUrl:'../../assets/images/landscape.png',
        title:'b',
        description:'bb'
      },
      {
        imageUrl:'../../assets/images/landscape.png',
        title:'c',
        description:'cc'
      },
      {
        imageUrl:'../../assets/images/landscape.png',
        title:'a',
        description:'aa'
      },
      {
        imageUrl:'../../assets/images/landscape.png',
        title:'b',
        description:'bb'
      },
      {
        imageUrl:'../../assets/images/landscape.png',
        title:'c',
        description:'cc'
      },
      {
        imageUrl:'../../assets/images/landscape.png',
        title:'a',
        description:'aa'
      },
      {
        imageUrl:'../../assets/images/landscape.png',
        title:'b',
        description:'bb'
      },
      {
        imageUrl:'../../assets/images/landscape.png',
        title:'c',
        description:'cc'
      }
    ]
  },
  onLoad(){
    console.log('onLoad');
  },
  onReachBottom(){
    // console.log('触底了');
    const data = [...this.data.entities,...this.data.entities];
    this.setData({
      entities:data
    })
  }
})